### ISSUE TITLE
This demo doesn't work

### ISSUE THREAD

**Issue by MacPu** [Moxtra/moxtra-chat-ios-sample#1]
Hi
I run this demo with ChatSDK v4.4.6, and I created a new chat, I got a crash. crash log like this:

` MoxieChat[20702:21051886] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010fa7d1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010dcae031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010faf2975 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010d692dd7 -[NSPlaceholderString initWithFormat:locale:arguments:] + 115
	4   Foundation                          0x000000010d6a0b08 +[NSString stringWithFormat:] + 169
	5   MoxieChat                           0x000000010c24c625 _ZN9MXCVector8GetIndexEPv + 111231
	6   MoxieChat                           0x000000010bf5c904 HRDrawSquareColorBatch + 1221670
	7   MoxieChat                           0x000000010bf50689 HRDrawSquareColorBatch + 1171883
	8   UIKit                               0x0000000112dd7131 -[UIViewController loadViewIfRequired] + 1215
	9   UIKit                               0x0000000112dd7574 -[UIViewController view] + 27
	10  MoxieChat                           0x000000010c1eeba1 processPathElementCallback + 190449
	11  MoxieChat                           0x000000010bdc5f59 trim + 375152
	12  MoxieChat                           0x000000010bb94e3e __27-[ViewController startMeet]_block_invoke + 94
	13  MoxieChat                           0x000000010bc3d6d5 MXfill_fopen_filefunc + 222013
	14  MoxieChat                           0x000000010c1eb7a9 processPathElementCallback + 177145
	15  MoxieChat                           0x000000010bcdb7a5 HSVColorAt + 391528
	16  MoxieChat                           0x000000010c15e05d MXAspectScaleFit + 48478
	17  MoxieChat                           0x000000010c0a6487 CGPDFDocumentNeedsPassword + 142285
	18  MoxieChat                           0x000000010c5412ec _ZNSt3__16__treeIyNS_4lessIyEENS_9allocatorIyEEE25__emplace_unique_key_argsIyJRKyEEENS_4pairINS_15__tree_iteratorIyPNS_11__tree_nodeIyPvEElEEbEERKT_DpOT0_ + 73348
	19  MoxieChat                           0x000000010c5585dd _ZNSt3__16__treeIyNS_4lessIyEENS_9allocatorIyEEE25__emplace_unique_key_argsIyJRKyEEENS_4pairINS_15__tree_iteratorIyPNS_11__tree_nodeIyPvEElEEbEERKT_DpOT0_ + 168309
	20  MoxieChat                           0x000000010c557c47 _ZNSt3__16__treeIyNS_4lessIyEENS_9allocatorIyEEE25__emplace_unique_key_argsIyJRKyEEENS_4pairINS_15__tree_iteratorIyPNS_11__tree_nodeIyPvEElEEbEERKT_DpOT0_ + 165855
	21  MoxieChat                           0x000000010c568401 _ZNSt3__16__treeIyNS_4lessIyEENS_9allocatorIyEEE25__emplace_unique_key_argsIyJRKyEEENS_4pairINS_15__tree_iteratorIyPNS_11__tree_nodeIyPvEElEEbEERKT_DpOT0_ + 233369
	22  MoxieChat                           0x000000010c52f1a4 _ZN16MXISDKCoreBridge10OnResponseERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_ + 210
	23  MoxieChat                           0x000000010c7a8540 _ZN11MXObjectMgr15SendSdkResponseERNSt3__110shared_ptrIN4Json5ValueEEE + 96
	24  MoxieChat                           0x000000010c7ccd96 _ZN11MXObjectMgr24OnSubscribeBoardCallbackERNSt3__110shared_ptrI14ClientResponseEERNS1_I13ClientRequestEERNS1_I14CMXResponseTagEERNS1_IN4Json5ValueEEESE_ + 1274
	25  MoxieChat                           0x000000010c7cac15 _ZN11MXObjectMgr16OnClientResponseERNSt3__110shared_ptrI14ClientResponseEERNS1_I13ClientRequestEERNS1_I14CMXResponseTagEE + 1431
	26  MoxieChat                           0x000000010c843235 _ZN6moxtra17internal_sdk_core9WebSocket20MainThreadHelperProcEjll + 993
	27  MoxieChat                           0x000000010c84351d _ZThn8_N6moxtra17internal_sdk_core9WebSocket20MainThreadHelperProcEjll + 13
	28  MoxieChat                           0x000000010c83798d _ZN11MxAppThread11PostMessageEjll + 231
	29  CoreFoundation                      0x000000010fa1fb0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	30  CoreFoundation                      0x000000010fa042db __CFRunLoopDoBlocks + 331
	31  CoreFoundation                      0x000000010fa0406b __CFRunLoopRun + 2795
	32  CoreFoundation                      0x000000010fa0330b CFRunLoopRunSpecific + 635
	33  GraphicsServices                    0x0000000116f68a73 GSEventRunModal + 62
	34  UIKit                               0x0000000112c33057 UIApplicationMain + 159
	35  MoxieChat                           0x000000010bb9692f main + 111
	36  libdyld.dylib                       0x0000000115036955 start + 1
	37  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

' start meet' also crashed like this.

**Comment by ken-moxtra** [comment]
@MacPu 
Guess you missed 'ChatSDKResource.bundle'
Please follow the [guide](https://developer.moxtra.com):
>Unzip the downloaded file and add the ChatSDK.framework and ChatSDKResource.bundle into your Xcode project by dragging them into your Project Navigator

**Comment by MacPu** [comment]
its works, thx
